import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import SystemProvider from '@/components/systemContext';
import { Toaster } from 'sonner';
import ReactScan from '@/components/reactScan';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Chat Dify',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactScan />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0, viewport-fit=cover"
      />
      <link rel="dns-prefetch" href="https://yamazaki.buzz/" />
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Toaster position="top-center" />
        <SystemProvider>{children}</SystemProvider>
      </body>
    </html>
  );
}
